# -*- coding: utf-8 -*-
"""OASIS_Task1_Iris_Flower_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdbiCAV5dXl1EAEb3B08S15P6G5on3Yf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

iris = load_iris()

X = iris.data
y = iris.target

print("Dataset loaded successfully!")
print("Features:", iris.feature_names)
print("Target names:", iris.target_names)
print("Dataset shape:", X.shape)

df = pd.DataFrame(X, columns=iris.feature_names)
df["species"] = y

print(df.head())

print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDescriptive Statistics:")
print(df.describe())

df["species_name"] = df["species"].map({
    0: "Setosa",
    1: "Versicolor",
    2: "Virginica"
})

print(df.head())

sns.pairplot(
    df,
    hue="species_name",
    vars=iris.feature_names
)

plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

model1 = LogisticRegression(max_iter=200)

model1.fit(X_train, y_train)

y_pred1 = model1.predict(X_test)

accuracy1 = accuracy_score(y_test, y_pred1)

print("Logistic Regression Accuracy:", accuracy1)
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred1,
    target_names=iris.target_names
))

model2 = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model2.fit(X_train, y_train)

y_pred2 = model2.predict(X_test)

accuracy2 = accuracy_score(y_test, y_pred2)

print("Random Forest Accuracy:", accuracy2)
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred2,
    target_names=iris.target_names
))

cm = confusion_matrix(y_test, y_pred2)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=iris.target_names,
    yticklabels=iris.target_names
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Random Forest")
plt.show()

print("Model Comparison")
print("------------------------")
print("Logistic Regression:", accuracy1)
print("Random Forest:", accuracy2)

new_flower = [[5.1, 3.5, 1.4, 0.2]]

prediction = model2.predict(new_flower)

print("Predicted Flower:",
      iris.target_names[prediction[0]])

"""Conclusion:

In this project, I performed Iris flower classification using
Machine Learning. I loaded the Iris dataset, performed basic
exploratory data analysis and visualization, and divided the
dataset into training and testing sets.

I trained Logistic Regression and Random Forest classification
models and evaluated them using accuracy, precision, recall and
F1-score.

This project helped me understand the basic workflow of a
machine learning classification problem.
"""